version: "3.8"
services:
  client:
    build: "./client"
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - myApp
  server:
    build: "./server"
    ports:
      - "5000:5000"
    networks:
      - myApp
networks:
  myApp:
    driver: bridge
